Create .github/dependabot.yml
awslabs/iot-application pull request #111
Opened 2023-04-08 20:53 UTC by tracy-french

Enable Dependabot upgrades.

## Legal

This project is available under the [Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0.html).

2023-04-10 17:22 UTC, square-li requested changes

2023-04-10 17:22 UTC, square-li commented on .github/dependabot.yml
> +# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
Thanks for these notes!

2023-04-10 17:22 UTC, square-li commented on .github/dependabot.yml
> +  - package-ecosystem: "npm" # See documentation for possible values
Should we use `yarn` instead? 

Ref: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem

2023-04-10 23:36 UTC, mumanity approved these changes

2023-04-11 13:44 UTC, square-li approved these changes

2023-04-11 14:13 UTC, merged