feat: added a build button that takes user directly to edit mode #1281
awslabs/iot-application pull request #1409
Opened 2023-10-06 12:26 UTC by Priyanshu44

![image](https://github.com/awslabs/iot-application/assets/81667589/ace7e25c-61b0-4741-baf8-2f1060970e06)

Issue: 
-> https://github.com/awslabs/iot-application/issues/1277
-> https://github.com/awslabs/iot-application/issues/1281

Description: When a user creates a dashboard, they should be brought directly to the edit mode & Add a new "build" button next to the "view" button, which opens the dashboard directly in "edit" mode

Changes done in the CR:
-> User redirected to edit mode on creating dashboard.
-> Added a new build button, which opens the dashboard directly in edit mode.

2023-10-06 13:19 UTC, mnischay submitted a review, later dismissed

2023-10-12 14:40 UTC, corteggiano commented
please pull latest changes from main so that the tests+lints can run :)

2023-10-12 15:39 UTC, mnischay requested changes
Also, please rebase with the lastest rc branch

2023-10-13 13:13 UTC, Priyanshu44 commented on apps/client/src/hooks/dashboard/use-emit-viewmode.ts
> +export function useEmitEditMode() {
resolved

2023-10-13 13:14 UTC, Priyanshu44 commented on apps/client/src/hooks/dashboard/use-viewmode.ts
> +  return useAtomValue(isEditModeVisibleAtom);
resolved

2023-10-16 15:37 UTC, Priyanshu44 commented
Issue resolved

2023-10-17 14:47 UTC, mnischay approved these changes

2023-10-18 10:13 UTC, Priyanshu44 commented
Created another PR from main repo so closing this one

2023-10-18 10:13 UTC, closed without merging