feat: wcag 2.1 aa compliance update #1916
awslabs/iot-application pull request #1529
Opened 2023-10-20 16:09 UTC by Pushpajyothi

Issue : https://github.com/awslabs/iot-app-kit/issues/1916

Description :
Added @axe-core/playwright package to create automation test suites for accessibility.
Created automation test suites to check WCAG 2.1 AA Compliance Accessibility issues.
Playwright test cmd will also run accessibility tests.(yarn run test:e2e)

Note : For now we have skip the testcases so that PR can merge.

2023-10-23 15:32 UTC, tracy-french commented
@Pushpajyothi Linting is failing. Could you take a look at that?

2023-10-23 15:34 UTC, tracy-french requested changes

2023-10-23 15:34 UTC, tracy-french commented on tests/accessibility/accessibility.ts
> +export async function accessibilityTest(page: Page) {
Accessibility testing! Nice!

2023-10-23 15:34 UTC, tracy-french commented on tests/accessibility/create-dashboard.spec.ts
> +test.skip(' Accessibility > As a user, I can verify Create Dashboard Page ', async ({
When do we stop skipping the tests?

2023-10-23 19:46 UTC, dpportet requested changes

2023-10-23 19:46 UTC, dpportet commented on tests/pages/dashboards-index.page.ts
> +    //Added View Button
If you run `yarn lint:fix` it should fix a lot of spacing issues like adding a space after the comment `//`.

2023-10-24 14:08 UTC, mnischay requested changes
Nice, i was under the impression that all the accessibility test are ran as a different step in GH actions ... i dont see those changes.

2023-10-28 17:49 UTC, closed without merging

2023-10-28 17:49 UTC, Pushpajyothi commented
Due to conflicts closed this PR and raised new PR in IoT application