feat: Accessibility Dashboard Created Confirmation Message #1840
awslabs/iot-application pull request #1868
Opened 2023-12-14 09:15 UTC by Priyanshu44

Issue: https://github.com/awslabs/iot-application/issues/1840

Fix:
->Use role="status" for status notifications.

2023-12-14 16:28 UTC, dpportet commented
LG but we'll have to figure out what's going on with the playwright tests, it's failing with:

```
Expected string: "Successfully updated dashboard \"My Dashboard\"."
    Received string: "Successfully updated dashboard \"My Dashboard\".Success Successfully updated dashboard \"My Dashboard\"."
```

2023-12-18 15:05 UTC, mnischay approved these changes

2023-12-18 15:06 UTC, mnischay requested changes
can you please merge your 2 commits into one

2023-12-18 18:16 UTC, Priyanshu44 commented
> can you please merge your 2 commits into one



> can you please merge your 2 commits into one

@mnischay done

2023-12-20 16:39 UTC, mnischay approved these changes

2023-12-20 16:40 UTC, merged