fix: save display settings in local storage
awslabs/iot-application pull request #1907
Opened 2024-01-05 12:47 UTC by Chandru-HM

# Description

This PR is for ticket https://github.com/awslabs/iot-app-kit/issues/2313 and display settings are now saved in local storage. 

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Display settings are now stored in local storage, verified saving the dashboard settings and refreshing the screen or switching to different dashboard.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Legal

This project is available under the [Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0.html).

2024-01-05 16:30 UTC, tracy-french requested changes
It looks good and is functional, but can we please write either unit, integration, or Playwright tests to ensure the functionality is maintained? Thank you! :)

2024-01-08 15:53 UTC, tracy-french approved these changes

2024-01-08 15:54 UTC, tracy-french commented
Thank you @Chandru-HM! Unfortunately, we now have a merge conflict on the test file as we updated `rc`. Could you please resolve that and we'll merge right away?

2024-01-08 16:04 UTC, Chandru-HM commented
> Thank you @Chandru-HM! Unfortunately, we now have a merge conflict on the test file as we updated `rc`. Could you please resolve that and we'll merge right away?

Updated. please have a look.

2024-01-08 16:14 UTC, tracy-french approved these changes

2024-01-08 16:14 UTC, tracy-french commented
Thank you @Chandru-HM!

2024-01-08 16:14 UTC, merged